import{a as m,S as p,i as l}from"./assets/vendor-CNpXvI_o.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const h="48830775-40ff68ea61f2bc47ba43ee541",g="https://pixabay.com/api/";function y(o){return m.get(g,{params:{key:h,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(t=>t.data.hits).catch(t=>{throw console.error("Error fetching data from Pixabay API:",t),t})}const b=document.querySelector("#gallery");let c=null;function L(o){const t=o.map(({largeImageURL:i,webformatURL:s,tags:e,likes:r,views:a,comments:f,downloads:d})=>`
    <a href="${i}" class="gallery-item">
      <img src="${s}" alt="${e}" />
      <div class="image-info">
        <p><b>Likes</b> ${r}</p>
        <p><b>Views</b> ${a}</p>
        <p><b>Comments</b> ${f}</p>
        <p><b>Downloads</b> ${d}</p>
      </div>
    </a>
  `).join("");b.innerHTML=t,c?c.refresh():c=new p(".gallery a",{captionsData:"alt",captionDelay:250})}const n={form:document.querySelector("#search-form"),input:document.querySelector("#search-input"),loader:document.querySelector("#loader"),gallery:document.querySelector("#gallery")};function S(){n.loader.classList.remove("hidden")}function u(){n.loader.classList.add("hidden")}function P(o){o.preventDefault();const t=n.input.value.trim();if(!t){l.error({title:"Error",message:"Oops! You forgot to enter a search term.",position:"topRight",timeout:2e3});return}S(),n.gallery.innerHTML="",y(t).then(i=>{u(),i.length===0?l.info({title:"Oops!",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3e3}):L(i)}).catch(()=>{u(),l.error({title:"Error",message:"Something went wrong! Please try again later.",position:"topRight",timeout:3e3})})}n.form.addEventListener("submit",P);
//# sourceMappingURL=index.js.map
